CREATE TABLE `miyoushe_55221094`
(
    `game_id`             INT          NOT NULL COMMENT '游戏的社区，2为原神',
    `post_id`             VARCHAR(50)  NOT NULL COMMENT '帖子ID',
    `reply_id`            VARCHAR(50)  NOT NULL COMMENT '评论ID',
    `uid`                 VARCHAR(50)  NOT NULL COMMENT '用户ID',
    `r_uid`               VARCHAR(50)  DEFAULT '0' COMMENT '回复的用户ID (为0时表示这是一级评论)',
    `content`             TEXT         NOT NULL COMMENT '评论内容',
    `f_forum_id`          INT          NOT NULL COMMENT '未知字段',
    `floor_id`            INT          NOT NULL COMMENT '楼ID (评论第几楼)',
    `is_deleted`          TINYINT(1)   DEFAULT 0 COMMENT '是否删除 (逻辑删除标记)',
    `delete_src`          INT          DEFAULT 0 COMMENT '删除源',
    `created_at`          BIGINT       NOT NULL COMMENT '创建时间戳 (发评论时间)',
    `deleted_at`          BIGINT COMMENT '删除时间戳',
    `struct_content`      TEXT         NOT NULL COMMENT '评论格式化字符串',
    `is_top`              TINYINT(1)   DEFAULT 0 COMMENT '是否置顶',
    `has_block_word`      TINYINT(1)   DEFAULT 0 COMMENT '是否包含屏蔽词',
    `overt_status`        TINYINT(1)   DEFAULT 0 COMMENT '公开状态，1表示公开',
    `is_showing_missing`  TINYINT(1)   DEFAULT 0 COMMENT '是否显示缺失',
    `view_status`         TINYINT(1)   DEFAULT 0 COMMENT '显示状态',
    `nickname`            VARCHAR(100) NOT NULL COMMENT '用户昵称',
    `gender`              TINYINT(1)   DEFAULT 0 COMMENT '性别',
    `certification_type`  TINYINT(1)   DEFAULT 0 COMMENT '用户认证类型',
    `certification_label` VARCHAR(100) DEFAULT '' COMMENT '用户认证标签',
    `level`               INT          DEFAULT 0 COMMENT '用户等级',
    `exp`                 INT          DEFAULT 0 COMMENT '用户经验',
    `ip_region`           VARCHAR(100) DEFAULT '' COMMENT 'IP地址',
    `like_num`            INT          DEFAULT 0 COMMENT '点赞数',
    `sub_num`             INT          DEFAULT 0 COMMENT '回复数',
    `dislike_num`         INT          DEFAULT 0 COMMENT '点踩数',
    `is_official_master`  TINYINT(1)   DEFAULT 0 COMMENT '是否官方',
    `is_user_master`      TINYINT(1)   DEFAULT 0 COMMENT '未知字段',
    PRIMARY KEY (`reply_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='米游社评论表_55221094';