server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reptile
    username: root
    password: 123456




mybatis-plus:
#  global-config:
#    db-config:
#      id-type: assign-id # 使用雪花算法生成 ID
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 控制台输出sql语句
    map-underscore-to-camel-case: true

  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.reptile.entity # 实体类包名

